config/routes.rb
TinapshahBlog::Application.routes.draw do

  resources :posts

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body, :title, :author
  validates :body, :title, :author, presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def index
		@name = "Tina"
		# @post_titles = ["Why code", "What I learned in 3 weeks"]
		# lesson 17 of http://learn.themakersquare.com/pages/rails/practicing-building-a-new-rails-app
		@posts = Post.all.sort_by{|p| p[:title]}
	end

	def show
		@post = Post.find(params[:id])
	end

	def new
		@post = Post.new
	end

	def create
	@post = Post.new(params[:post])
		if @post.save
			redirect_to @post
		else
			flash[:notice] = "Enter a title and body."
			render action: 'new'
		end    
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
	@post = Post.find(params[:id])
	@post.update_attributes(params[:post])
		if @post.save
			redirect_to @post
		else
			render action: 'edit'
		end 
	end

	def destroy
	@post = Post.find(params[:id])
	@post.destroy
	redirect_to posts_path
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css" rel="stylesheet">
  <title>TinapshahBlog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.haml
= form_for @post do |p| 
 = p.label :title, 'Title:'
 = p.text_field :title 
 %br
 = p.label :author, 'Author:'
 = p.text_field :author
 %br
 = p.label :body, 'Body:'
 %span#text_field
 = p.text_field :body
 %br
  = p.submit

app/views/posts/edit.html.haml
%h1 Edit a blog post! Woo!


= render "form"

app/views/posts/index.html.haml
%body
	%h1 #{@name}'s Blog
	%p
	%br
	%br
	= link_to "New Post", new_post_path
	- @posts.each do |entry|
		%h3
			=link_to "#{entry.title}",post_path(entry)
		%p	
			=link_to "Edit", edit_post_path(entry)
			|
			=link_to "Delete", entry, :method => :delete, :data => {confirm: 'you sure?'}
		%br

	- if flash[:notice].present?
		%p= flash[:notice]

app/views/posts/new.html.haml
%h1 Create a new blog post! Woo!

- if flash[:notice].present?
		%p= flash[:notice]


= render "form"
=link_to "Back to Index", posts_path

app/views/posts/show.html.haml
%h1= @post.title

%p= @post.body


=link_to "Edit", edit_post_path
|
=link_to "Delete", @post, :method => :delete, :data => {confirm: 'you sure?'}
|
=link_to "Back to Index", posts_path
|
= link_to "New Post", new_post_path